CREATE TABLE [dbo].[CustomSkin](
	[Name] [varchar](10) NOT NULL,
	[SkinNumber] [tinyint] NOT NULL,
 CONSTRAINT [PK_CustomSkin] PRIMARY KEY CLUSTERED 
(
	[Name] ASC,
	[SkinNumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]




