CREATE TABLE [dbo].[CustomStore](
	[Name] [varchar](10) NOT NULL,
	[Active] [tinyint] NOT NULL DEFAULT (0),
	[Type] [smallint] NOT NULL DEFAULT (0),
	[StoreName] [varchar](36) NULL,
 CONSTRAINT [PK_CustomStore] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

