ALTER TABLE MEMB_INFO ADD OnlineRewardTime1 smallint NOT NULL DEFAULT (0)
ALTER TABLE MEMB_INFO ADD OnlineRewardTime2 smallint NOT NULL DEFAULT (0)
ALTER TABLE MEMB_INFO ADD OnlineRewardTime3 smallint NOT NULL DEFAULT (0)



