CREATE TABLE [dbo].[EventEntryCount](
	[Name] [varchar](10) NOT NULL,
	[Type] [int] NOT NULL,
	[EntryCount] [int] NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_EventEntryCount] PRIMARY KEY CLUSTERED 
(
	[Name] ASC,
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]