ALTER TABLE AccountCharacter ADD GameID6 VARCHAR(10) NULL
GO
ALTER TABLE AccountCharacter ADD GameID7 VARCHAR(10) NULL
GO
ALTER TABLE AccountCharacter ADD GameID8 VARCHAR(10) NULL
GO
ALTER TABLE AccountCharacter ADD GameID9 VARCHAR(10) NULL
GO
ALTER TABLE AccountCharacter ADD GameID10 VARCHAR(10) NULL
GO